#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test

echo ""
echo "====== pre-commit prettier修复、eslint、stylelint校验 ======"
echo ""

npx pretty-quick --staged # prettier 格式化修复
npx lint-staged # 校验